.. -*-restructuredtext-*-

==============================
QtalBomber game specifications
==============================


Used softwares 
--------------

    * UML modeling: ArgoUML 0.30
    * Programming language: C++
    * C++ compiler: GNU g++ 4.4
    * Graphical framework: Qt 4.6  
    * SCM: git 1.7


Miscellaneous
-------------

1. Text document format

Technical documents that are written in ReST format.
For more information see: http://en.wikipedia.org/wiki/ReStructuredText

2. Official code repository 

http://github.com/jexhson/qtalbomber


Game play
---------

TODO: Translate and refactor

A chaque fin de round un nbr de point est attribué au joueurs (3 pour le
gagnant, 2 pour le second, etc…) qui servira à déterminer le gagnant à l'issu
des n rounds

Donc mode de jeu survivant, le dernier en vie gagne le round peu importe le nbr
de kill
ex : J1 tue J2 & J3 mais se suicide par inadvertance => J4 gagne le round sans
avoir tué personne.


